import { test, expect, canvasNode, load } from './helpers'
test('updates a Business Hours range and timezone while branch nodes stay read-only', async ({ page }) => {
  await load(page)
  await canvasNode(page, 'd09c08').click()
  const drawer = page.getByRole('dialog')
  await expect(drawer.locator('[data-testid="day-row"]')).toHaveCount(7)
  const startTime = drawer.getByLabel('Monday start time')
  await startTime.click()
  const hours = page.getByRole('listbox', { name: 'Hours' })
  const minutes = page.getByRole('listbox', { name: 'Minutes' })
  const selectedHour = hours.getByRole('option', { name: '10', exact: true })
  await selectedHour.click()
  await expect(selectedHour).toHaveCSS('background-color', 'rgb(109, 92, 231)')
  await minutes.getByRole('option', { name: '07', exact: true }).click()
  await expect(startTime).toContainText('10:07')
  await startTime.click()
  await expect(hours.getByRole('option', { name: '10', exact: true })).toHaveCSS('background-color', 'rgb(109, 92, 231)')
  await expect(minutes.getByRole('option', { name: '07', exact: true })).toHaveCSS('background-color', 'rgb(109, 92, 231)')
  await page.keyboard.press('Escape')
  await drawer.getByLabel('Timezone').click()
  await expect(page.getByRole('option')).toHaveCount(24)
  await page.getByRole('option', { name: /Asia\/Dhaka$/ }).click()
  await drawer.getByRole('button', { name: 'Save changes' }).click()
  await page.keyboard.press('Escape')
  await canvasNode(page, 'd09c08').click()
  await expect(drawer.getByLabel('Monday start time')).toContainText('10:07')
  await expect(drawer.getByLabel('Timezone')).toContainText('Asia/Dhaka')
  await page.keyboard.press('Escape')
  await canvasNode(page, '28c4b9').click()
  await expect(page).toHaveURL(/\/$/)
  await expect(page.getByRole('dialog')).not.toBeVisible()
})
