import { test, expect, canvasNode, load } from './helpers'
test('updates a Business Hours range and timezone while branch nodes stay read-only', async ({ page }) => {
  await load(page)
  await canvasNode(page, 'd09c08').click()
  const drawer = page.getByRole('dialog')
  await expect(drawer.locator('[data-testid="day-row"]')).toHaveCount(7)
  await drawer.getByLabel('Monday start time').fill('10:15')
  await drawer.getByLabel('Timezone').click()
  await expect(page.getByRole('option')).toHaveCount(24)
  await page.getByRole('option', { name: /Asia\/Dhaka$/ }).click()
  await drawer.getByRole('button', { name: 'Save changes' }).click()
  await page.keyboard.press('Escape')
  await canvasNode(page, 'd09c08').click()
  await expect(drawer.getByLabel('Monday start time')).toHaveValue('10:15')
  await expect(drawer.getByLabel('Timezone')).toContainText('Asia/Dhaka')
  await page.keyboard.press('Escape')
  await canvasNode(page, '28c4b9').click()
  await expect(page).toHaveURL(/\/$/)
  await expect(page.getByRole('dialog')).not.toBeVisible()
})
