import { test, expect, canvasNode, load } from './helpers'
test('updates and removes an Add Comment note', async ({ page }) => {
  await load(page)
  await canvasNode(page, 'e879e4').click()
  const drawer = page.getByRole('dialog')
  await expect(drawer.getByLabel('Comment')).toHaveValue('User message during off hours')
  await drawer.getByLabel('Comment').fill('Follow up tomorrow')
  await drawer.getByRole('button', { name: 'Save changes' }).click()
  await page.keyboard.press('Escape')
  await canvasNode(page, 'e879e4').click()
  await expect(drawer.getByLabel('Comment')).toHaveValue('Follow up tomorrow')
  await drawer.getByRole('button', { name: 'Remove comment' }).click()
  await drawer.getByRole('button', { name: 'Save changes' }).click()
  await expect(drawer.getByLabel('Comment')).toHaveValue('')
})
