import { test, expect, load } from './helpers'
test('create validates empty fields and adds a new node to the canvas', async ({ page }) => {
  await load(page)
  const source = page.locator('.vue-flow__node[data-id="b0653a"]')
  const sourceAdd = source.getByRole('button', { name: 'Add node after Welcome Message' })
  await expect(sourceAdd).toHaveCSS('color', 'rgb(152, 162, 179)')
  await sourceAdd.click()
  const dialog = page.getByRole('dialog')
  await dialog.getByRole('button', { name: 'Create node', exact: true }).click()
  await expect(dialog.getByText('Use at least 3 characters')).toBeVisible()
  await dialog.getByLabel('Title', { exact: true }).fill('Follow up')
  await dialog.getByLabel('Description', { exact: true }).fill('Send a helpful follow up')
  await dialog.getByLabel('Type', { exact: true }).selectOption('addComment')
  await dialog.getByRole('button', { name: 'Create node', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.locator('.vue-flow__node')).toHaveCount(8)
  const created = page.locator('.vue-flow__node').filter({ hasText: 'Follow up' })
  await expect(created).toBeVisible()
  await expect(sourceAdd).toHaveCSS('color', 'rgb(92, 142, 232)')
  await expect(created.getByRole('button', { name: 'Add node after Follow up' })).toHaveCSS('color', 'rgb(152, 162, 179)')
})
test('a node plus opens the drawer and inserts a connected node directly after it', async ({ page }) => {
  await load(page)
  const source = page.locator('.vue-flow__node[data-id="b6a0c1"]')
  const previousChild = page.locator('.vue-flow__node[data-id="e879e4"]')
  const sourceBox = await source.boundingBox()
  const previousChildBox = await previousChild.boundingBox()
  await source.getByRole('button', { name: 'Add node after Away Message' }).click()
  const drawer = page.getByRole('dialog')
  await expect(drawer).toContainText('Add after Away Message')
  await drawer.getByLabel('Title', { exact: true }).fill('Continue welcome')
  await drawer.getByLabel('Description', { exact: true }).fill('The next welcome step')
  await drawer.getByRole('button', { name: 'Create node', exact: true }).click()
  await expect(page.locator('.vue-flow__node')).toHaveCount(8)
  await expect(page.locator('.vue-flow__edge')).toHaveCount(7)
  await expect(source.getByRole('button', { name: 'Add node after Away Message' })).toBeVisible()
  const created = page.locator('.vue-flow__node').filter({ hasText: 'Continue welcome' })
  const createdBox = await created.boundingBox()
  expect(Math.abs(createdBox.x - sourceBox.x)).toBeLessThan(2)
  expect(createdBox.y).toBeGreaterThan(sourceBox.y)
  const movedChildBox = await previousChild.boundingBox()
  expect(movedChildBox.y).toBeGreaterThan(previousChildBox.y)
  await expect(created.getByRole('button', { name: 'Add node after Continue welcome' })).toBeVisible()
})
