import { test, expect, canvasNode, load, dragNode } from './helpers'
test('keyboard undo and redo restore a real move and a saved edit', async ({ page }) => {
  await load(page)
  const node = canvasNode(page, 'b0653a')
  const originalStyle = await node.getAttribute('style')
  await dragNode(page, 'b0653a', 100, 50)
  await expect(node).not.toHaveAttribute('style', originalStyle)
  await page.locator('.vue-flow__pane').click({ position: { x: 20, y: 20 } })
  await page.keyboard.press('ControlOrMeta+z')
  await expect(node).toHaveAttribute('style', originalStyle)
  await page.keyboard.press('ControlOrMeta+Shift+z')
  await expect(node).not.toHaveAttribute('style', originalStyle)
  await node.click()
  const drawer = page.getByRole('dialog')
  await drawer.getByLabel('Title', { exact: true }).fill('Undo this edit')
  await drawer.getByRole('button', { name: 'Save changes' }).click()
  await page.keyboard.press('Escape')
  await page.keyboard.press('ControlOrMeta+z')
  await expect(node).toContainText('Welcome Message')
  await page.keyboard.press('ControlOrMeta+Shift+z')
  await expect(node).toContainText('Undo this edit')
})
